auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: 不被了解的怪人
url: http://dramapolice.github.io
feed: /atom.xml
author_info: <a href="http://dramapolice.github.io/">Michelangelo</a>
